<?php
declare(strict_types=1);
require_once __DIR__.'/includes/bootstrap.php';
$user=require_login();$csrf=csrf_token();
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Converter - <?=e(APP_NAME)?></title><style>body{font-family:Arial;background:#0b1020;color:#e5e7eb;margin:0}.wrap{max-width:900px;margin:auto;padding:30px}.nav{display:flex;gap:10px;margin-bottom:24px}.nav a{color:#fff;text-decoration:none;background:#1e293b;padding:10px 14px;border-radius:8px}.card{background:#151d33;padding:24px;border-radius:18px;border:1px solid #26304a;margin-bottom:18px}input,select,button{padding:12px;border-radius:9px;border:1px solid #3b4763;background:#0f172a;color:#fff}input[type=file]{width:100%;box-sizing:border-box}button{background:#6366f1;border:0;font-weight:700;cursor:pointer}.row{display:grid;grid-template-columns:1fr 1fr;gap:14px}.result{margin-top:16px;padding:14px;border-radius:10px;background:#0f172a;white-space:pre-wrap}.ok{border:1px solid #22c55e}.err{border:1px solid #ef4444}@media(max-width:650px){.row{grid-template-columns:1fr}}</style></head><body><div class="wrap"><div class="nav"><a href="dashboard.php">Dashboard</a><a href="converter.php">Converter</a><a href="files.php">File Manager</a></div><div class="card"><h1>🎵 Audio → MIDI</h1><p>Upload audio yang Anda miliki. File akan divalidasi dan dibaca menggunakan FFprobe.</p><input type="hidden" id="csrf" value="<?=e($csrf)?>"><input id="audio" type="file" accept=".mp3,.wav,.m4a,.flac,.ogg,.aac,audio/*"><div class="row" style="margin-top:14px"><label>Mode<select id="mode" style="display:block;width:100%;margin-top:6px"><option value="automatic">Automatic</option><option value="melody">Melody</option><option value="polyphonic">Polyphonic</option><option value="piano">Piano</option><option value="bass">Bass</option><option value="vocals">Vocals</option><option value="percussion">Percussion</option></select></label><div><button id="upload" style="margin-top:25px;width:100%">Upload & Baca Metadata</button></div></div><div id="result" class="result">Belum ada file.</div></div><div class="card"><h2>Antrean Konversi</h2><p id="jobText">Upload file lalu buat job konversi.</p><button id="convert" disabled>Masukkan ke Queue</button><button id="cancel" disabled style="margin-left:8px;background:#7f1d1d">Batalkan</button></div></div><script>
let fileId=null,jobId=null,timer=null;
const result=document.getElementById('result'),convert=document.getElementById('convert'),cancel=document.getElementById('cancel');
const show=(x,ok=true)=>{result.textContent=x;result.className='result '+(ok?'ok':'err');};
document.getElementById('upload').onclick=async()=>{
 const f=document.getElementById('audio').files[0];if(!f)return show('Pilih file audio terlebih dahulu.',false);
 const fd=new FormData();fd.append('audio',f);fd.append('_csrf',document.getElementById('csrf').value);
 show('Mengunggah dan menjalankan FFprobe...');
 try{const r=await fetch('api/upload/audio.php',{method:'POST',body:fd});const j=await r.json();if(!j.success)throw new Error(j.message);fileId=j.data.file_id;show('Upload berhasil.\n'+JSON.stringify(j.data.metadata,null,2));convert.disabled=false;}catch(e){show(e.message,false);}
};
convert.onclick=async()=>{
 const fd=new FormData();fd.append('_csrf',document.getElementById('csrf').value);fd.append('file_id',fileId);fd.append('mode',document.getElementById('mode').value);
 try{const r=await fetch('api/converter/create.php',{method:'POST',body:fd});const j=await r.json();if(!j.success)throw new Error(j.message);jobId=j.data.job_id;convert.disabled=true;cancel.disabled=false;document.getElementById('jobText').textContent='Job '+jobId+' dibuat. Status: queued';poll();}catch(e){show(e.message,false);}
};
async function poll(){if(timer)clearTimeout(timer);try{const r=await fetch('api/converter/status.php?job_id='+encodeURIComponent(jobId));const j=await r.json();if(!j.success)throw new Error(j.message);const x=j.data.job;document.getElementById('jobText').textContent='Job '+x.job_id+' | '+x.status+' | '+x.progress+'%'+(x.error?' | '+x.error:'');if(['queued','processing'].includes(x.status))timer=setTimeout(poll,2000);else cancel.disabled=true;}catch(e){document.getElementById('jobText').textContent=e.message;}}
cancel.onclick=async()=>{const fd=new FormData();fd.append('_csrf',document.getElementById('csrf').value);fd.append('job_id',jobId);const r=await fetch('api/converter/cancel.php',{method:'POST',body:fd});const j=await r.json();document.getElementById('jobText').textContent=j.message;cancel.disabled=true;if(timer)clearTimeout(timer);};
</script></body></html>