<?php
declare(strict_types=1);
require_once __DIR__.'/includes/bootstrap.php';
$user=require_login();$csrf=csrf_token();
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MIDI Quality Dashboard</title>
<style>
body{font-family:Inter,Arial,sans-serif;background:#070b16;color:#e8eefc;margin:0}.wrap{max-width:1180px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:18px}.top a{color:#fff;text-decoration:none;background:#172036;padding:10px 14px;border-radius:10px}.card{background:#11192b;border:1px solid #263452;border-radius:18px;padding:20px;margin-bottom:18px;box-shadow:0 12px 30px #0003}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:#0b1222;border-radius:14px;padding:16px}.stat b{display:block;font-size:28px;margin-top:6px}input,select,textarea,button{box-sizing:border-box;background:#0a1020;color:#fff;border:1px solid #33415f;border-radius:9px;padding:10px}button{background:#6366f1;border:0;font-weight:700;cursor:pointer}button.danger{background:#991b1b}.controls{display:grid;grid-template-columns:1fr 1fr;gap:14px}.version{display:flex;justify-content:space-between;align-items:center;gap:12px;background:#0b1222;padding:14px;border-radius:12px;margin-top:8px}.muted{color:#93a4c4;font-size:13px}.score{font-size:42px;font-weight:800}@media(max-width:800px){.grid,.controls{grid-template-columns:1fr 1fr}}@media(max-width:550px){.grid,.controls{grid-template-columns:1fr}.version{display:block}.version button{margin-top:8px}}
</style></head><body><div class="wrap">
<div class="top"><div><h1>🎛️ MIDI Quality Dashboard</h1><div class="muted">Kelola kualitas, A/B result, versi, dan re-processing MIDI.</div></div><a href="converter.php">← Converter</a></div>
<div class="card"><h2>1. Pilih MIDI</h2><select id="file" style="width:100%"><option value="">Memuat file...</option></select><div id="fileInfo" class="muted" style="margin-top:10px"></div></div>
<div class="card"><h2>2. Quality Controls</h2><div class="controls"><label>Confidence Threshold <input id="min" type="range" min="1" max="127" value="20" style="width:100%"><span id="minVal">20</span><div class="muted">Velocity proxy untuk confidence.</div></label><label>Quantization Strength <input id="quant" type="range" min="0" max="100" value="72" style="width:100%"><span id="quantVal">72%</span></label></div><p><label><input id="harm" type="checkbox" checked> Harmonic / duplicate cleanup</label></p><label>Track / Instrument Override<textarea id="overrides" rows="5" style="width:100%;margin-top:7px" placeholder='{"0":{"name":"Lead Vocals","type":"vocals"}}'></textarea></label><p><button id="reprocess">🔄 Re-process MIDI</button></p><div id="job" class="muted"></div></div>
<div class="card"><h2>3. A/B Quality Statistics</h2><div class="grid"><div class="stat">Original Tracks<b id="ot">-</b></div><div class="stat">Final Tracks<b id="ft">-</b></div><div class="stat">Removed Notes<b id="rn">-</b></div><div class="stat">Final Notes<b id="fn">-</b></div></div><div style="margin-top:16px">Quality Score <span id="score" class="score">-</span>/100</div><pre id="report" style="white-space:pre-wrap;background:#0a1020;padding:14px;border-radius:12px;overflow:auto"></pre></div>
<div class="card"><h2>4. Version History</h2><div id="versions">Pilih MIDI untuk melihat versi.</div></div>
</div><script>
const csrf='<?=e($csrf)?>';const $=id=>document.getElementById(id);
$('min').oninput=()=>{$('minVal').textContent=$('min').value};$('quant').oninput=()=>{$('quantVal').textContent=$('quant').value+'%'};
function score(q){if(!q||!q.original_tracks)return 0;const original=q.original_notes||q.final_notes+(q.removed_low_confidence||0)+(q.removed_duplicates||0);const final=q.final_notes||0;if(!original)return 100;const retention=final/original;const cleanup=(q.removed_duplicates||0)+(q.removed_low_confidence||0);return Math.max(0,Math.min(100,Math.round(70*retention+30*Math.min(1,cleanup/Math.max(1,original)*4))))}
async function loadFiles(){const r=await fetch('api/files/list.php?type=midi');const j=await r.json();if(!j.success)return;$('file').innerHTML='<option value="">-- Pilih MIDI --</option>'+(j.data.files||[]).map(f=>'<option value="'+f.id+'">'+escapeHtml(f.original_name)+'</option>').join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function load(){const id=$('file').value;if(!id)return;$('fileInfo').textContent='Memuat quality report...';const q=await fetch('api/midi/quality.php?file_id='+id).then(r=>r.json());if(q.success){const x=q.data.quality||{};$('ot').textContent=x.original_tracks??'-';$('ft').textContent=x.final_tracks??'-';$('rn').textContent=(x.removed_low_confidence||0)+(x.removed_duplicates||0);$('fn').textContent=x.final_notes??'-';$('score').textContent=score(x);$('report').textContent=JSON.stringify(x,null,2)}loadVersions(id)}
async function loadVersions(id){const j=await fetch('api/midi/versions.php?file_id='+id).then(r=>r.json());if(!j.success)return;$('versions').innerHTML=j.data.versions.length?j.data.versions.map(v=>'<div class="version"><div><b>v'+v.version_number+' — '+escapeHtml(v.label)+'</b><div class="muted">'+v.created_at+' · '+(v.is_current?'CURRENT':'archive')+'</div></div><button onclick="restoreVersion('+v.id+')">↩ Restore</button></div>').join(''):'Belum ada version history.'}
async function restoreVersion(id){const fd=new FormData();fd.append('_csrf',csrf);fd.append('version_id',id);const j=await fetch('api/midi/restore-version.php',{method:'POST',body:fd}).then(r=>r.json());alert(j.message);if($('file').value)loadVersions($('file').value)}
$('file').onchange=load;$('reprocess').onclick=async()=>{const id=$('file').value;if(!id)return alert('Pilih MIDI.');const fd=new FormData();fd.append('_csrf',csrf);fd.append('file_id',id);fd.append('min_velocity',$('min').value);fd.append('quantize_strength',Number($('quant').value)/100);fd.append('harmonic_cleanup',$('harm').checked?'1':'0');fd.append('track_overrides',$('overrides').value||'{}');const j=await fetch('api/midi/reprocess.php',{method:'POST',body:fd}).then(r=>r.json());$('job').textContent=j.message+(j.data?.job_id?' Job: '+j.data.job_id:'');if(j.success)setTimeout(()=>poll(j.data.job_id),1500)}
async function poll(id){const j=await fetch('api/converter/status.php?job_id='+id).then(r=>r.json());if(j.success){$('job').textContent='Re-process '+j.data.job.status+' — '+j.data.job.progress+'%';if(['queued','processing'].includes(j.data.job.status))return setTimeout(()=>poll(id),2000);if(j.data.job.status==='completed')setTimeout(load,500)}}
loadFiles();
</script></body></html>