#!/usr/bin/env python3
"""PHASE 10 MIDI intelligence and quality refinement.

Works on real MIDI generated by the PHASE 9 neural pipeline.  The refiner is
deliberately MIDI-domain based: confidence is represented by the source MIDI
velocity when the transcription engine does not expose a portable confidence
sidecar.  All operations are deterministic and configurable.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from collections import defaultdict
import mido

TPB_DEFAULT = 480
GM_PROGRAMS = {
    "vocals": 53,      # Voice Oohs
    "bass": 33,        # Electric Bass (finger)
    "drums": 0,        # channel 9 uses GM percussion mapping
    "piano": 0,        # Acoustic Grand Piano
    "other": 48,       # String Ensemble 1, neutral melodic fallback
    "melody": 53,
    "polyphonic": 0,
}

def clamp(v, lo, hi):
    return max(lo, min(hi, v))

def beat_to_ticks(beat, tpb):
    return int(round(beat * tpb))

def ticks_to_beat(ticks, tpb):
    return ticks / float(tpb)

def adaptive_grid_ticks(note, tpb):
    """Choose a grid from note length: shorter notes keep a finer grid."""
    dur = max(1, note["end"] - note["start"])
    if dur <= tpb // 4:
        return max(1, tpb // 16)
    if dur <= tpb:
        return max(1, tpb // 8)
    if dur <= tpb * 2:
        return max(1, tpb // 4)
    return max(1, tpb // 2)

def nearest_grid(value, grid):
    return int(round(value / grid) * grid)

def velocity_normalize(notes, floor=28, ceiling=112):
    if not notes:
        return
    vals = [n["velocity"] for n in notes]
    lo, hi = min(vals), max(vals)
    if hi <= lo:
        for n in notes:
            n["velocity"] = clamp(max(floor, n["velocity"]), 1, 127)
        return
    for n in notes:
        scaled = floor + (n["velocity"] - lo) * (ceiling - floor) / (hi - lo)
        n["velocity"] = clamp(int(round(scaled)), 1, 127)

def remove_duplicates(notes, onset_window=24, harmonic_window=0):
    """Remove same-pitch collisions and optional near-unison harmonic duplicates."""
    notes.sort(key=lambda n: (n["start"], n["pitch"], -n["velocity"]))
    kept = []
    buckets = defaultdict(list)
    for n in notes:
        key = (n["pitch"], n["channel"])
        duplicate = False
        for old in reversed(buckets[key]):
            if n["start"] - old["start"] > onset_window:
                break
            overlap = min(n["end"], old["end"]) - max(n["start"], old["start"])
            if overlap > 0 or abs(n["start"] - old["start"]) <= onset_window:
                duplicate = True
                if n["velocity"] > old["velocity"]:
                    old.update(n)
                break
        if duplicate:
            continue
        if harmonic_window:
            for old in reversed(kept):
                if n["start"] - old["start"] > onset_window:
                    break
                if abs(n["pitch"] - old["pitch"]) <= harmonic_window and n["pitch"] != old["pitch"]:
                    overlap = min(n["end"], old["end"]) - max(n["start"], old["start"])
                    if overlap > 0 and n["velocity"] <= old["velocity"] + 6:
                        duplicate = True
                        break
        if not duplicate:
            kept.append(n)
            buckets[key].append(n)
    return kept

def merge_adjacent(notes, max_gap=18):
    notes.sort(key=lambda n: (n["channel"], n["pitch"], n["start"]))
    out = []
    for n in notes:
        if out:
            p = out[-1]
            if (p["channel"], p["pitch"]) == (n["channel"], n["pitch"]) and n["start"] - p["end"] <= max_gap:
                p["end"] = max(p["end"], n["end"])
                p["velocity"] = max(p["velocity"], n["velocity"])
                continue
        out.append(dict(n))
    return out

def quantize_adaptive(notes, tpb, strength=0.72):
    for n in notes:
        grid = adaptive_grid_ticks(n, tpb)
        target = nearest_grid(n["start"], grid)
        shift = int(round((target - n["start"]) * strength))
        n["start"] = max(0, n["start"] + shift)
        dur = max(1, n["end"] - n["start"])
        end_target = nearest_grid(n["end"], grid)
        end_shift = int(round((end_target - n["end"]) * strength))
        n["end"] = max(n["start"] + 1, n["end"] + end_shift)
        # Keep very short events musical rather than collapsing them.
        if n["end"] - n["start"] < max(1, tpb // 16):
            n["end"] = n["start"] + max(1, tpb // 16)

def extract_tracks(mid):
    tracks = []
    for idx, tr in enumerate(mid.tracks):
        abs_tick = 0
        active = {}
        notes = []
        name = f"Track {idx + 1}"
        channel_program = {}
        for msg in tr:
            abs_tick += msg.time
            if msg.type == "track_name":
                name = msg.name or name
            elif msg.type == "program_change":
                channel_program[msg.channel] = msg.program
            elif msg.type == "note_on" and msg.velocity > 0:
                active[(msg.channel, msg.note)] = (abs_tick, msg.velocity)
            elif msg.type in ("note_off", "note_on") and (msg.type == "note_off" or msg.velocity == 0):
                key = (msg.channel, msg.note)
                if key in active:
                    start, vel = active.pop(key)
                    notes.append({
                        "start": start, "end": max(start + 1, abs_tick),
                        "pitch": msg.note, "velocity": vel, "channel": msg.channel,
                    })
        if notes:
            tracks.append({"index": idx, "name": name, "notes": notes, "programs": channel_program})
    return tracks

def classify_track(name, source_stem=None):
    s = (source_stem or name).lower()
    for key in ("vocals", "voice", "vocal"):
        if key in s: return "Vocals", "vocals"
    if "drum" in s or "perc" in s: return "Drums", "drums"
    if "bass" in s: return "Bass", "bass"
    if "piano" in s or "keys" in s: return "Piano", "piano"
    if "melody" in s: return "Melody", "melody"
    return "Instrument", "other"

def build_track(name, notes, tpb, program, channel):
    track = mido.MidiTrack()
    track.append(mido.MetaMessage("track_name", name=name, time=0))
    events = []
    if channel != 9:
        events.append((0, 0, mido.Message("program_change", channel=channel, program=program, time=0)))
    for n in notes:
        events.append((n["start"], 1, mido.Message("note_on", channel=channel, note=n["pitch"], velocity=n["velocity"], time=0)))
        events.append((n["end"], 0, mido.Message("note_off", channel=channel, note=n["pitch"], velocity=0, time=0)))
    events.sort(key=lambda x: (x[0], x[1]))
    last = 0
    for tick, _, msg in events:
        msg.time = max(0, tick - last)
        track.append(msg)
        last = tick
    return track

def refine(input_path, output_path, mode="automatic", min_velocity=20,
           quantize_strength=0.72, harmonic_cleanup=True):
    mid = mido.MidiFile(str(input_path))
    tpb = mid.ticks_per_beat or TPB_DEFAULT
    source_tracks = extract_tracks(mid)
    all_notes = []
    refined_tracks = []
    report = {
        "engine": "phase10-midi-intelligence",
        "input": str(input_path),
        "mode": mode,
        "ticks_per_beat": tpb,
        "original_tracks": len(source_tracks),
        "tracks": [],
        "removed_low_confidence": 0,
        "removed_duplicates": 0,
        "merged_notes": 0,
        "quantized_notes": 0,
    }

    # A neural MIDI has velocity but not a portable per-note confidence field.
    # Treat low velocity as a conservative confidence proxy.
    for tr in source_tracks:
        kept = [dict(n) for n in tr["notes"] if n["velocity"] >= min_velocity]
        report["removed_low_confidence"] += len(tr["notes"]) - len(kept)
        before = len(kept)
        kept = remove_duplicates(kept, harmonic_window=1 if harmonic_cleanup else 0)
        report["removed_duplicates"] += before - len(kept)
        before_merge = len(kept)
        kept = merge_adjacent(kept)
        report["merged_notes"] += before_merge - len(kept)
        velocity_normalize(kept)
        quantize_adaptive(kept, tpb, quantize_strength)
        report["quantized_notes"] += len(kept)
        label, kind = classify_track(tr["name"], tr["name"])
        if kind == "drums":
            channel = 9
            program = 0
        else:
            channel = next((n["channel"] for n in kept), 0)
            if channel == 9:
                channel = 0
            program = GM_PROGRAMS.get(kind, 0)
        refined_tracks.append((f"{label} {len(refined_tracks)+1}", kind, kept, program, channel))
        all_notes.extend(kept)

    out = mido.MidiFile(type=1, ticks_per_beat=tpb)
    # Preserve a tempo map, falling back to 120 BPM.
    tempo_events = []
    for tr in mid.tracks:
        tick = 0
        for msg in tr:
            tick += msg.time
            if msg.type == "set_tempo":
                tempo_events.append((tick, msg.tempo))
    meta = mido.MidiTrack()
    meta.append(mido.MetaMessage("track_name", name="Tempo / Master", time=0))
    if tempo_events:
        last = 0
        for tick, tempo in sorted(set(tempo_events)):
            meta.append(mido.MetaMessage("set_tempo", tempo=tempo, time=max(0, tick-last)))
            last = tick
        report["tempo_bpm"] = round(mido.tempo2bpm(tempo_events[0][1]), 2)
    else:
        meta.append(mido.MetaMessage("set_tempo", tempo=mido.bpm2tempo(120), time=0))
        report["tempo_bpm"] = 120.0
    out.tracks.append(meta)

    for name, kind, notes, program, channel in refined_tracks:
        if not notes:
            continue
        out.tracks.append(build_track(name, notes, tpb, program, channel))
        report["tracks"].append({
            "name": name, "type": kind, "notes": len(notes),
            "program": program, "channel": channel,
            "confidence_proxy": "source MIDI velocity",
        })

    out.save(str(output_path))
    report["final_tracks"] = len(out.tracks) - 1
    report["final_notes"] = sum(x["notes"] for x in report["tracks"])
    Path(str(output_path) + ".json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    return report

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--mode", default="automatic")
    ap.add_argument("--min-velocity", type=int, default=20)
    ap.add_argument("--quantize-strength", type=float, default=0.72)
    ap.add_argument("--no-harmonic-cleanup", action="store_true")
    args = ap.parse_args()
    report = refine(args.input, args.output, args.mode,
                    clamp(args.min_velocity, 1, 127),
                    clamp(args.quantize_strength, 0, 1),
                    not args.no_harmonic_cleanup)
    print(json.dumps(report))

if __name__ == "__main__":
    main()
