-- MIDI CONVERTER STUDIO - XAMPP / MariaDB
-- Database: midi_converter_studio
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
CREATE DATABASE IF NOT EXISTS midi_converter_studio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE midi_converter_studio;

CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role ENUM('user','admin') NOT NULL DEFAULT 'user',plan ENUM('free','pro') NOT NULL DEFAULT 'free',status ENUM('active','suspended','pending') NOT NULL DEFAULT 'active',storage_used_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,last_login_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS files (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,type ENUM('audio','midi','cover','other') NOT NULL,original_name VARCHAR(255) NOT NULL,stored_name VARCHAR(255) NOT NULL,relative_path VARCHAR(500) NOT NULL,mime_type VARCHAR(120) NOT NULL,extension VARCHAR(20) NOT NULL,size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,duration_seconds DECIMAL(12,3) NULL,sample_rate INT UNSIGNED NULL,channels TINYINT UNSIGNED NULL,metadata_json JSON NULL,status ENUM('active','deleted','processing','failed') NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,INDEX idx_files_user_type(user_id,type),INDEX idx_files_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS conversions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,source_file_id BIGINT UNSIGNED NOT NULL,output_file_id BIGINT UNSIGNED NULL,job_id VARCHAR(100) NOT NULL UNIQUE,mode ENUM('melody','polyphonic','piano','bass','vocals','percussion','automatic') NOT NULL DEFAULT 'automatic',status ENUM('queued','processing','completed','failed','cancelled') NOT NULL DEFAULT 'queued',progress TINYINT UNSIGNED NOT NULL DEFAULT 0,processing_engine VARCHAR(100) NULL,settings_json JSON NULL,error_message TEXT NULL,started_at DATETIME NULL,completed_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(source_file_id) REFERENCES files(id) ON DELETE CASCADE,FOREIGN KEY(output_file_id) REFERENCES files(id) ON DELETE SET NULL,INDEX idx_conversions_user_created(user_id,created_at),INDEX idx_conversions_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS midi_tracks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,file_id BIGINT UNSIGNED NOT NULL,track_index INT UNSIGNED NOT NULL,name VARCHAR(190) NULL,channel TINYINT UNSIGNED NULL,instrument SMALLINT UNSIGNED NULL,volume TINYINT UNSIGNED NULL,pan TINYINT UNSIGNED NULL,muted TINYINT(1) NOT NULL DEFAULT 0,solo TINYINT(1) NOT NULL DEFAULT 0,FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE CASCADE,UNIQUE KEY uq_midi_tracks_file_index(file_id,track_index)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS midi_notes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,track_id BIGINT UNSIGNED NOT NULL,pitch SMALLINT NOT NULL,start_tick BIGINT UNSIGNED NOT NULL,duration_ticks BIGINT UNSIGNED NOT NULL,velocity TINYINT UNSIGNED NOT NULL DEFAULT 100,channel TINYINT UNSIGNED NULL,FOREIGN KEY(track_id) REFERENCES midi_tracks(id) ON DELETE CASCADE,INDEX idx_midi_notes_track_tick(track_id,start_tick)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `usage` (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,usage_month CHAR(7) NOT NULL,conversions_count INT UNSIGNED NOT NULL DEFAULT 0,storage_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,UNIQUE KEY uq_usage_user_month(user_id,usage_month)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS password_resets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expires_at DATETIME NOT NULL,used_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS activity_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,action VARCHAR(120) NOT NULL,entity_type VARCHAR(80) NULL,entity_id BIGINT UNSIGNED NULL,ip_address VARCHAR(45) NULL,user_agent VARCHAR(500) NULL,details_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_activity_logs_user_created(user_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,setting_key VARCHAR(190) NOT NULL UNIQUE,setting_value TEXT NULL,setting_type ENUM('string','integer','boolean','json') NOT NULL DEFAULT 'string',is_public TINYINT(1) NOT NULL DEFAULT 0,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO settings(setting_key,setting_value,setting_type,is_public) VALUES ('free_monthly_conversions','5','integer',0),('free_max_file_mb','20','integer',0),('free_storage_mb','500','integer',0),('pro_monthly_conversions','50','integer',0),('pro_max_file_mb','100','integer',0),('pro_storage_mb','5120','integer',0),('app_name','MIDI Converter Studio','string',1) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),setting_type=VALUES(setting_type),is_public=VALUES(is_public);
CREATE TABLE IF NOT EXISTS midi_quality_versions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,file_id BIGINT UNSIGNED NOT NULL,parent_file_id BIGINT UNSIGNED NULL,version_number INT UNSIGNED NOT NULL DEFAULT 1,label VARCHAR(190) NOT NULL,settings_json JSON NULL,quality_json JSON NULL,is_current TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE CASCADE,FOREIGN KEY(parent_file_id) REFERENCES files(id) ON DELETE SET NULL,INDEX idx_quality_versions_file_created(file_id,created_at),INDEX idx_quality_versions_parent(parent_file_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;
SELECT 'MIDI Converter Studio database ready for XAMPP' AS status;